#jinja2: lstrip_blocks: True
---
{#
# In this file users, backendroles and hosts can be mapped to Open Distro Security roles.
# Permissions for Opendistro roles are configured in roles.yml
#}

_meta:
  type: "rolesmapping"
  config_version: 2

# Define your roles mapping here

all_access:
  reserved: false
  backend_roles:
    - "admin"
  description: "Maps admin to all_access"

security_rest_api_access:
  reserved: false
  users:
    - "elastic"
  description: "Allow access to security_rest_api"

own_index:
  reserved: false
  users:
    - "*"
  description: "Allow full access to an index named like the username"

{% if ldap_admin_group is defined and ldap_admin_group | length > 0 and ldap_admin_group is iterable %}
{% for admin_group in ldap_admin_group %}
{{ admin_group }}:
  reserved: false
  backend_roles:
    - "{{ admin_group }}"
  hosts: []
  users: []
  description: "admins, managed with ansible"
{% endfor %}
{% endif %}
{% if ldap_read_user_group is defined and ldap_read_user_group | length > 0 and ldap_read_user_group is iterable%}
{% for read_user_group in ldap_read_user_group %}
{{ read_user_group }}:
  reserved: false
  backend_roles:
    - "{{ read_user_group }}"
  hosts: []
  users: []
  description: "regular users, managed with ansible"
{% endfor %}
{% endif %}
