---
# opendistro related
opendistro_version: "1.12.0"
elasticsearch_version: "7.10.0"
kibana_version: "7.10.0"
es_plugin_bin_path: /usr/share/elasticsearch/bin/elasticsearch-plugin
es_sec_plugin_conf_path: /usr/share/elasticsearch/plugins/opendistro_security/securityconfig
es_sec_plugin_tools_path: /usr/share/elasticsearch/plugins/opendistro_security/tools
# defaault 60 min
opendistro_security_cache_ttl_minutes: 540
opendistro_ldap_enabled: "{% if ldap_admin_group is defined and ldap_admin_group | length > 0 and ldap_admin_group is iterable %}true{% elif ldap_read_user_group is defined and ldap_read_user_group | length > 0 and ldap_read_user_group is iterable %}true{% else %}false{% endif %}"
prom_elasticsearchexporter_version: '1.1.0'
prom_nodeexporter_version: 'v0.18.1'
prom_cadvisor_version: 'v0.34.0'
prom_redis_version: '6.0.8'
exporter_dict:
  elasticsearch_exporter:
    version: "{{ prom_elasticsearchexporter_version }}"
    repo: "justwatch"
  node-exporter:
    version: "{{ prom_nodeexporter_version }}"
    repo: "prom"
  cadvisor:
    version: "{{ prom_cadvisor_version }}"
    repo: "gcr.io/google-containers"
  redis:
    version: "{{ prom_redis_version }}"
    repo: ""
